# Generated by Django 2.0.2 on 2018-02-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=250)),
                ('name_am', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Opus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=500)),
                ('title_am', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500)),
                ('comment_ru', models.CharField(max_length=1000)),
                ('comment_am', models.CharField(max_length=1000)),
                ('comment_en', models.CharField(max_length=1000)),
                ('year', models.DateField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Genre', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_url', models.CharField(max_length=1000)),
                ('title_ru', models.CharField(max_length=500, null=True)),
                ('title_am', models.CharField(max_length=500, null=True)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('performDate', models.DateField(null=True)),
                ('location', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname_ru', models.CharField(max_length=250)),
                ('lname_ru', models.CharField(max_length=250)),
                ('fname_am', models.CharField(max_length=250)),
                ('lname_am', models.CharField(max_length=250)),
                ('fname_en', models.CharField(max_length=250)),
                ('lname_en', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='performer',
            name='performer',
            field=models.ManyToManyField(to='catalog.Person', verbose_name='Автор текста'),
        ),
        migrations.AddField(
            model_name='performance',
            name='performers',
            field=models.ManyToManyField(to='catalog.Performer', verbose_name='Исполнители'),
        ),
        migrations.AddField(
            model_name='opus',
            name='libretto_by',
            field=models.ManyToManyField(related_name='libr_authors', to='catalog.Person', verbose_name='Автор либретто'),
        ),
        migrations.AddField(
            model_name='opus',
            name='lyrics_by',
            field=models.ManyToManyField(related_name='lyr_authors', to='catalog.Person', verbose_name='Автор текста'),
        ),
        migrations.AddField(
            model_name='opus',
            name='performance',
            field=models.ManyToManyField(to='catalog.Performance', verbose_name='Исполнения'),
        ),
    ]
