# Generated by Django 2.0.2 on 2018-09-04 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opus',
            old_name='performance',
            new_name='performances',
        ),
        migrations.AlterField(
            model_name='opus',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='opus',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
