# Generated by Django 2.0.2 on 2018-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180904_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
