# Generated by Django 2.0.2 on 2018-09-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180910_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fname_am',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='fname_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lname_am',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lname_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
