# Generated by Django 2.0.2 on 2018-09-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180914_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name_am',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
